baseURL = "https://techotters.org/"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
languageCode = "ru-RU"
title = "tech {otters}"
theme = "anubis2"

[params]
sectionPagesMenu = "main"
mainSections = ["instructions", "reviews", "news"]
description = "Мы тестируем, лечим и продлеваем жизнь гаджетам! Профессиональные обзоры, инструкции и хитрости ремонта, чтобы техника служила дольше."
dateFormat = "02.01.2006"
paginationSinglePost = true
customCSS = ["css/custom1.css"]
colorTheme = "auto"
colorThemeSwitcher = true
version = "0.3.1"
githubUsername = "KenGuRU25"
githubRepoName = "tech-otters"
readMore = true
readNextPosts = 2
copyCodeButton = true
locale = "ru-RU"
math = false
toc = true
disableRobotsTXT = true
social = [
    { id = "telegram", url = "https://t.me/techotters" },
]

[permalinks]
instructions = "/categories/instructions/:slug/"
reviews = "/categories/reviews/:slug/"
news = "/categories/news/:slug/"
faq = "/categories/faq/:slug/"
authors = "/authors/:slug/"

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1
    contentDir = "content/ru"
  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

[[languages.en.menu.main]]
identifier = "categories"
name = "Publications"
url = "/categories/"
weight = 1

[[languages.en.menu.main]]
identifier = "contacts"
name = "Members"
url = "/authors/"
weight = 2

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[languages.ru.menu.main]]
identifier = "categories"
name = "Публикации"
url = "/categories/"
weight = 1

[[languages.ru.menu.main]]
identifier = "contacts"
name = "Участники"
url = "/authors/"
weight = 2

[[languages.ru.menu.main]]
identifier = "about"
name = "О проекте"
url = "/about/"
weight = 3

[languages.ru.params]
languageCode = "ru-RU"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "e406deb4-702a-43c9-8fb3-aae309ad18b5"                                            # Website ID
datacache = false
url = "https://cloud.umami.is/script.js"
shareUrl = "https://cloud.umami.is/share/kDZiId8LR7dr8qgc/techotters.org"