baseURL = "https://tpedia.ru/"
defaultContentLanguage = "ru"
languageCode = "ru-ru"
title = "techpedia"
theme = "anubis2"

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
mainSections = ["instructions", "reviews"]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "02.01.2006"
paginationSinglePost = true
customCSS = ["css/custom1.css"]
colorTheme = "auto"
colorThemeSwitcher = true

readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

social = [
    { id = "instagram", url = "#" },
    { id = "telegram", url = "#" },
    { id = "youtube", url = "#" },
    { id = "vk", url = "#" },
    { id = "email", url = "mail@techpedia.ru" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[[languages.ru.menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 1

[[languages.ru.menu.main]]
identifier = "instruction"
name = "шаг за шагом"
url = "/instructions/"
weight = 2

[[languages.ru.menu.main]]
identifier = "reviews"
name = "в деталях"
url = "/reviews/"
weight = 3

[[languages.ru.menu.main]]
identifier = "about"
name = "о проекте"
url = "/about/"
weight = 4

[languages.ru.params]
languageCode = "ru-ru"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "a9e02222-e74e-475d-9fac-01599029baef"                                            # Website ID
datacache = false
url = "https://cloud.umami.is/script.js"
shareUrl = "https://cloud.umami.is/share/ljpurhir3DRoeMcd/tpedia.ru"