baseURL = "https://tpedia.ru/"
defaultContentLanguage = "ru"
languageCode = "ru-RU"
title = "tech otters"
theme = "anubis2"

[permalinks]
instructions = "/categories/instructions/:slug/"
reviews = "/categories/reviews/:slug/"

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
defaultContentLanguageInSubdir = true
mainSections = ["instructions", "reviews"]
description = "Профессиональные обзоры устройств и подробные инструкции для устранения их дефектов."
dateFormat = "02.01.2006"
paginationSinglePost = true
customCSS = ["css/custom1.css"]
colorTheme = "auto"
colorThemeSwitcher = true
version = "0.2.0-alpha"
githubUsername = "KenGuRU25"
githubRepoName = "tech-otters"
readMore = true
readNextPosts = 2
copyCodeButton = true
locale = "ru-RU"
math = false
toc = true
disableRobotsTXT = true
social = [
    { id = "instagram", url = "#" },
    { id = "telegram", url = "#" },
    { id = "youtube", url = "#" },
    { id = "vk", url = "#" },
    { id = "email", url = "mail@techpedia.ru" }
]

[[menu.main]]
identifier = "categories"
name = "Post"
url = "/categories/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[languages.ru.menu.main]]
identifier = "categories"
name = "Статьи"
url = "/categories/"
weight = 1

[[languages.ru.menu.main]]
identifier = "about"
name = "О проекте"
url = "/about/"
weight = 2

[languages.ru.params]
languageCode = "ru-RU"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "a9e02222-e74e-475d-9fac-01599029baef"                                            # Website ID
datacache = false
url = "https://cloud.umami.is/script.js"
shareUrl = "https://cloud.umami.is/share/ljpurhir3DRoeMcd/tpedia.ru"